/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FacultyDetailsForm.java
 *
 * Created on Jan 23, 2012, 8:35:16 PM
 */
package test;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
/**
 *
 * @author Administrator
 */
public class FacultyDetailsForm extends javax.swing.JFrame {
    String action="";
    int tempID;
    public FacultyDetailsForm() {
        
        initComponents();
        setLocationRelativeTo(null);
        Thread thd = new Thread(){
            @Override
        public void run(){
        Component video;
        video = Webcam.cam.getVideo();
        if(video != null){
            video.setSize(photo.getWidth(), photo.getHeight());
        } else {
            video = new Component() {};
        }
        photo.add(video,BorderLayout.CENTER);
        if(Webcam.cam.isLoaded() != false){
        Webcam.cam.startCam();
        }
        }
        };
        thd.start();
        this.photoPanel.hide();
        this.editPic.hide();
        tempID = Faculty.fct.generateFacultyID();
        this.facultyId.setText("FAC-"+tempID);
        int valid = Integer.parseInt(TimeDate.time.timestampToFullDate(System.currentTimeMillis()).substring(0, 4));
        facultyValidUpto.setText(Integer.toString(valid+2));
    }
    
    public FacultyDetailsForm(String type){
            //getPrevious();
        action=type;
        initComponents();
        setLocationRelativeTo(null);          
        this.photo.hide();
        this.capture.hide();
        if(Faculty.fct.image != null){
                ImageIcon thumbnailIcon = new ImageIcon(Utilities.util.rescaleImage(Faculty.fct.image,this.photoPanel.getWidth(),this.photoPanel.getHeight()));
                this.pic.setIcon(thumbnailIcon);
            }
        tempID = Faculty.fct.generateFacultyID();
        this.facultyId.setText("FAC-"+tempID);
    }   
    
    private void refreshID(){
        tempID = tempID + 1;
        this.facultyId.setText("FAC-"+tempID);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        facultyId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        facultyAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        facultyName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        facultyPhone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        facultyDept = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        facultyPost = new javax.swing.JTextField();
        facultyValidUpto = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        reset = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        photo = new javax.swing.JPanel();
        capture = new javax.swing.JToggleButton();
        photoPanel = new javax.swing.JPanel();
        pic = new javax.swing.JLabel();
        editPic = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(": : Faculty Registration : :");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                windowclse(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                windowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Faculty Registeration Form");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        facultyId.setBackground(new java.awt.Color(255, 255, 225));
        facultyId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        facultyId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        facultyId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                facultyIdKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Valid Upto:");

        cancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/button_cancel.png"))); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        cancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cancelKeyPressed(evt);
            }
        });

        submit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/checkin.png"))); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        submit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                submitKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Department:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Post:");

        facultyAddress.setBackground(new java.awt.Color(255, 255, 225));
        facultyAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        facultyAddress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        facultyAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                facultyAddressKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Address:");

        facultyName.setBackground(new java.awt.Color(255, 255, 225));
        facultyName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        facultyName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        facultyName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                facultyNameKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Phone no:");

        facultyPhone.setBackground(new java.awt.Color(255, 255, 225));
        facultyPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        facultyPhone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        facultyPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                facultyPhoneKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("ID:");

        facultyDept.setBackground(new java.awt.Color(255, 255, 225));
        facultyDept.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        facultyDept.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        facultyDept.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                facultyDeptKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Name:");

        facultyPost.setBackground(new java.awt.Color(255, 255, 225));
        facultyPost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        facultyPost.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        facultyPost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                facultyPostKeyPressed(evt);
            }
        });

        facultyValidUpto.setBackground(new java.awt.Color(255, 255, 225));
        facultyValidUpto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        facultyValidUpto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        facultyValidUpto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                facultyValidUptoKeyPressed(evt);
            }
        });

        reset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/refresh.png"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        reset.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                resetKeyPressed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/24/refresh.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(submit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reset)
                        .addGap(47, 47, 47)
                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(facultyPost)
                            .addComponent(facultyPhone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(facultyName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(facultyAddress, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(facultyDept, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(facultyValidUpto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(facultyId)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel11)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(facultyId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facultyName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(facultyAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(facultyPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(facultyDept, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facultyPost, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(facultyValidUpto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/64/faculty.png"))); // NOI18N

        photo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout photoLayout = new javax.swing.GroupLayout(photo);
        photo.setLayout(photoLayout);
        photoLayout.setHorizontalGroup(
            photoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );
        photoLayout.setVerticalGroup(
            photoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );

        jPanel2.add(photo);

        capture.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        capture.setText("Take Snapshot");
        capture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                captureActionPerformed(evt);
            }
        });
        capture.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                captureKeyPressed(evt);
            }
        });
        jPanel2.add(capture);

        photoPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout photoPanelLayout = new javax.swing.GroupLayout(photoPanel);
        photoPanel.setLayout(photoPanelLayout);
        photoPanelLayout.setHorizontalGroup(
            photoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        );
        photoPanelLayout.setVerticalGroup(
            photoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );

        jPanel2.add(photoPanel);

        editPic.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        editPic.setText("Edit Pic");
        editPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPicActionPerformed(evt);
            }
        });
        jPanel2.add(editPic);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addComponent(jLabel9))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        if(Webcam.cam.isLoaded()!=false){
            Webcam.cam.stopCam();
        }
        this.dispose();
}//GEN-LAST:event_cancelActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
submit();   
  
}//GEN-LAST:event_submitActionPerformed

    void submit()
    {   if(putFacultyInfo()){
          if(action.equalsIgnoreCase("edit")){
              FacultyDetails fctDetail = new FacultyDetails("edit");
              fctDetail.setVisible(true);
                }
          if(action.equalsIgnoreCase("delete")){
              FacultyDetails fctDetail = new FacultyDetails("delete");
              fctDetail.setVisible(true);
              }
          else if(action.equalsIgnoreCase("") || action.equalsIgnoreCase("back")){
            FacultyDetails fctDetail = new FacultyDetails(1);
            fctDetail.setVisible(true);
                }
             this.dispose();
        }
    }
    
        
    boolean putFacultyInfo(){
    if(Validation.val.validateFacultyInfo(this.facultyId.getText(),this.facultyName.getText(),this.facultyAddress.getText(),this.facultyPhone.getText(),this.facultyDept.getText(),this.facultyPost.getText(),this.facultyValidUpto.getText()) == true){            
        Faculty.fct.name = this.facultyName.getText();
        Faculty.fct.id = this.facultyId.getText();
        Faculty.fct.address = this.facultyAddress.getText();
        Faculty.fct.phone = this.facultyPhone.getText();
        Faculty.fct.profile = this.facultyPost.getText();
        Faculty.fct.department =this.facultyDept.getText();
        Faculty.fct.validUpto = Integer.parseInt(this.facultyValidUpto.getText());
        
        if(!action.equalsIgnoreCase("edit")){
        Faculty.fct.addtimestamp=TimeDate.time.timestampToFullDate(AbstractPerson.ab.currentTimeStamp());
        Faculty.fct.addedby=Session.s1.sessionUser;
        }
        Faculty.fct.password = this.facultyId.getText();
        return true;
        }
    else 
        return false;
    }
    void resetItems(){
        //enableItems();        
           
                this.facultyName.setText("");
                this.facultyPhone.setText("");
                this.facultyAddress.setText("");
                this.facultyDept.setText("");
                this.facultyPost.setText("");
                 }
     void getPrevious()
     {
           this.facultyId.setText(Faculty.fct.id);
                this.facultyName.setText(Faculty.fct.name);
                this.facultyPhone.setText(Faculty.fct.phone);
                this.facultyAddress.setText(Faculty.fct.address);
                this.facultyDept.setText(Faculty.fct.department);
                this.facultyPost.setText(Faculty.fct.profile);
                this.facultyValidUpto.setText(((Integer)Faculty.fct.validUpto).toString());    
     }
     
    private void windowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosed

    }//GEN-LAST:event_windowClosed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
resetItems();
            }//GEN-LAST:event_resetActionPerformed

    private void windowclse(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowclse
         if(Webcam.cam.isLoaded()!=false){
            Webcam.cam.closeCam();
        }
    }//GEN-LAST:event_windowclse

    private void captureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_captureActionPerformed

        if (capture.isSelected()) {
            Webcam.cam.captureImage();
            BufferedImage bi = Webcam.cam.getBufferedImage();
            Faculty.fct.image = bi;
            Faculty.fct.fingerprint = bi;
            Webcam.cam.stopCam();
        } else if (!capture.isSelected()) {
            Webcam.cam.startCam();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_captureActionPerformed

    private void editPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPicActionPerformed

        WebcamTest t = new WebcamTest("faculty");
        t.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_editPicActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked

        refreshID();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    void keyAction(java.awt.event.KeyEvent evt, String Button) {
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            if (Button.equalsIgnoreCase("cancel")) {
                int i=DialogBox.dialog.confirmDialog("All the details will get lost.. Do you want to cancel ??");
             if(i==0)
             {
                 this.dispose();
             }
             else if(i==1){}
             else if(i==2){}
            } 
            else if (Button.equalsIgnoreCase("submit")) {
                submit();
            }
            else if (Button.equalsIgnoreCase("reset")) {
                resetItems();
            }
            else{
            submit();
            }
        }
        if (key == KeyEvent.VK_ESCAPE) {    
             int i=DialogBox.dialog.confirmDialog("All the details will get lost.. Do you want to cancel ??");
             if(i==0)
             {
                 this.dispose();
             }
             else if(i==1){}
             else if(i==2){}
            }
    }
    private void facultyIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_facultyIdKeyPressed

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        facultyName.requestFocus();
        }
        else{
        keyAction(evt,"submit");
        }// TODO add your handling code here:
    }//GEN-LAST:event_facultyIdKeyPressed

    private void facultyNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_facultyNameKeyPressed

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        facultyAddress.requestFocus();
        }
        else{
        keyAction(evt,"submit");
        }// TODO add your handling code here:
    }//GEN-LAST:event_facultyNameKeyPressed

    private void facultyAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_facultyAddressKeyPressed

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        facultyPhone.requestFocus();
        }
        else{
        keyAction(evt,"submit");
        }// TODO add your handling code here:
    }//GEN-LAST:event_facultyAddressKeyPressed

    private void facultyPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_facultyPhoneKeyPressed

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        facultyDept.requestFocus();
        }
        else{
        keyAction(evt,"submit");
        }// TODO add your handling code here:
    }//GEN-LAST:event_facultyPhoneKeyPressed

    private void facultyDeptKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_facultyDeptKeyPressed

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        facultyPost.requestFocus();
        }
        else{
        keyAction(evt,"submit");
        }// TODO add your handling code here:
    }//GEN-LAST:event_facultyDeptKeyPressed

    private void facultyPostKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_facultyPostKeyPressed

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        facultyValidUpto.requestFocus();
        }
        else{
        keyAction(evt,"submit");
        }// TODO add your handling code here:
    }//GEN-LAST:event_facultyPostKeyPressed

    private void facultyValidUptoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_facultyValidUptoKeyPressed

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        capture.requestFocus();
        }
        else{
        keyAction(evt,"submit");
        }// TODO add your handling code here:
    }//GEN-LAST:event_facultyValidUptoKeyPressed

    private void captureKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_captureKeyPressed

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        submit.requestFocus();
        }
        else{
        keyAction(evt,"submit");
        }// TODO add your handling code here:
    }//GEN-LAST:event_captureKeyPressed

    private void submitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_submitKeyPressed
            keyAction(evt,"submit");
    }//GEN-LAST:event_submitKeyPressed

    private void resetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resetKeyPressed
        keyAction(evt,"reset");
    }//GEN-LAST:event_resetKeyPressed

    private void cancelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cancelKeyPressed
        keyAction(evt,"cancel");
    }//GEN-LAST:event_cancelKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JToggleButton capture;
    private javax.swing.JButton editPic;
    private javax.swing.JTextField facultyAddress;
    private javax.swing.JTextField facultyDept;
    private javax.swing.JTextField facultyId;
    private javax.swing.JTextField facultyName;
    private javax.swing.JTextField facultyPhone;
    private javax.swing.JTextField facultyPost;
    private javax.swing.JTextField facultyValidUpto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel photo;
    private javax.swing.JPanel photoPanel;
    private javax.swing.JLabel pic;
    private javax.swing.JButton reset;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
