/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FacultyDetails.java
 *
 * Created on Feb 6, 2012, 2:33:09 AM
 */
package test;

import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author Administrator
 */
public class FacultyDetails extends javax.swing.JFrame {

    /**
     * Creates new form FacultyDetails
     */
    private String ActionType = "";

    /**
     * Creates new form FacultyDetailsForm
     */
    public FacultyDetails(String type) {
        initComponents();
        setLocationRelativeTo(null);
        displayFacultyInfo();
        ActionType = type;
        if (type.equalsIgnoreCase("Edit")) {
            jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Are You sure You want to edit/delete this faculty?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 0)));
        }
    }

    public FacultyDetails(int i) {
        initComponents();
        setLocationRelativeTo(null);
        displayFacultyInfo();
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Is the above information correct?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 0)));
        
    }

    private void displayFacultyInfo() {
        this.name.setText(Faculty.fct.name);
        this.id.setText(Faculty.fct.id);
        this.phoneno.setText(Faculty.fct.phone);
        this.address.setText(Faculty.fct.address);
        this.dept.setText(Faculty.fct.department);
        this.post.setText(Faculty.fct.profile);
        this.validUpto.setText(((Integer) Faculty.fct.validUpto).toString());
        this.registeredat.setText(Faculty.fct.addtimestamp);
        if (Faculty.fct.image != null) {
            ImageIcon thumbnailIcon = new ImageIcon(Utilities.util.rescaleImage(Faculty.fct.image, this.photoPanel.getWidth(), this.photoPanel.getHeight()));
            this.pic.setIcon(thumbnailIcon);
        }        
    }

    public FacultyDetails(String rollNo, String name, String type) {
        
        if (Faculty.fct.setFacultyInfo(rollNo, name) == true) {
            initComponents();
            setLocationRelativeTo(null);
            displayFacultyInfo();
            ActionType = type;
            if (type.equalsIgnoreCase("submit")) {
                jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Are the information correct?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N
            }
            
            if (type.equalsIgnoreCase("edit/delete")) {
                back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/delete.png")));
                save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/edit.png")));
                this.save.setText("Edit");
                this.back.setText("Delete");
            }
            
            if (type.equalsIgnoreCase("view")) {
                save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/ok.png")));
                this.save.setText("Ok");
                this.back.hide();
            }
            if (type.equalsIgnoreCase("print")) {
                save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/print.png")));
                this.save.setText("Print");
                this.back.hide();
            }
            if (type.equalsIgnoreCase("resetpass")) {
                save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/change_pass.png")));
                this.save.setText("Reset");
                this.back.hide();
            }
            else {
                this.dispose();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        phoneno = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dept = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        post = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        validUpto = new javax.swing.JLabel();
        photoPanel = new javax.swing.JPanel();
        pic = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        registeredat = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        back = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(": : Faculty Details : :");
        setResizable(false);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Id");

        id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id.setForeground(new java.awt.Color(0, 0, 204));
        id.setText("109334");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Name");

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(0, 0, 204));
        name.setText("Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Phone no");

        phoneno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phoneno.setForeground(new java.awt.Color(0, 0, 204));
        phoneno.setText("phone");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Address");

        address.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        address.setForeground(new java.awt.Color(0, 0, 204));
        address.setText("Address");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Department");

        dept.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dept.setForeground(new java.awt.Color(0, 0, 204));
        dept.setText("department");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Post");

        post.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        post.setForeground(new java.awt.Color(0, 0, 204));
        post.setText("post");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setText("Valid Upto :");

        validUpto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        validUpto.setForeground(new java.awt.Color(0, 0, 204));
        validUpto.setText("valid upto");

        photoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout photoPanelLayout = new javax.swing.GroupLayout(photoPanel);
        photoPanel.setLayout(photoPanelLayout);
        photoPanelLayout.setHorizontalGroup(
            photoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        photoPanelLayout.setVerticalGroup(
            photoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        registeredat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        registeredat.setForeground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(registeredat, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registeredat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Registered At:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel17))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name)
                    .addComponent(dept)
                    .addComponent(phoneno)
                    .addComponent(address)
                    .addComponent(id)
                    .addComponent(post, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validUpto))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(photoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(id))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(address))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(phoneno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(dept))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(photoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(post)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(validUpto))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        save.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/add.PNG"))); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        save.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keySave(evt);
            }
        });

        back.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/back.png"))); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        back.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyBack(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/button_cancel.png"))); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        cancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyCancel(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Faculty Membership Information");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/64/faculty.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        submit();        
}//GEN-LAST:event_saveActionPerformed
    
    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        
        cancel();
}//GEN-LAST:event_cancelActionPerformed
    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        back();
    }//GEN-LAST:event_backActionPerformed
    
    void cancel() {
        this.dispose();
    }
    
    void submit() {
        if (this.ActionType.equalsIgnoreCase("")) {
            if (Faculty.fct.ifFacultyExists(Faculty.fct.id, "")) {
                DialogBox.dialog.successDialog("Faculty with " + Faculty.fct.id + " already exists");
                FacultyDetailsForm fctreg = new FacultyDetailsForm("back");
                fctreg.getPrevious();
                fctreg.setVisible(true);
            } else if (Faculty.fct.addFaculty() == true) {
                DialogBox.dialog.successDialog("faculty Record Sucessfully added");
                int choice = DialogBox.dialog.confirmDialog("Do you want to add another faculty??");
                if (choice == 0) {
                    FacultyDetailsForm fctreg = new FacultyDetailsForm();
                    fctreg.setVisible(true);
                } else {
                    this.dispose();
                }
            }
        } else if (this.ActionType.equalsIgnoreCase("edit")) {
            if (Faculty.fct.editFaculty() == true) {
                DialogBox.dialog.successDialog("Faculty record SucessFully Edited!!!");// TODO add your handling code here:
                EnterRoll er = new EnterRoll("edit/delete", "faculty");
                er.setVisible(true);
            }
        }
        else if (this.ActionType.equalsIgnoreCase("resetpass")) {
            PasswordResetBox pr = new PasswordResetBox(Faculty.fct.id,"faculty");
            pr.setVisible(true);
        }
        
        if (save.getText().equalsIgnoreCase("edit")) {
            FacultyDetailsForm fctreg = new FacultyDetailsForm("edit");
            fctreg.getPrevious();
            fctreg.setVisible(true);
        }
        if (save.getText().equalsIgnoreCase("print")) {
         Report rep = new Report();
         rep.printFacultyInfo(Faculty.fct.id);
        }
        

        /*
         * if(save.getText().equalsIgnoreCase("ok")) { EnterRoll er=new
         * EnterRoll("view","faculty"); er.setVisible(true); }
         */        
        this.dispose();        
    }

    void back() {
        if (back.getText().equalsIgnoreCase("delete")) {
            
            int i = DialogBox.dialog.confirmDialog("Are you sure you want to delete info of" + Faculty.fct.id + "?");
            if (i == 0) {
                if (Faculty.fct.deleteFaculty() == true) {
                    DialogBox.dialog.successDialog("faculty record SucessFully Deleted!!!");// TODO add your handling code here:
                } else {
                    DialogBox.dialog.errorDialog("Error in Deleting faculty's information");
                }
            }
            EnterRoll er = new EnterRoll("edit/delete", "faculty");
            er.setVisible(true);
        } else if (back.getText().equalsIgnoreCase("print")) {
            Report report = new Report();
            report.printFacultyInfo(Faculty.fct.id);
        } else {
            if (ActionType.equalsIgnoreCase("")) {
                FacultyDetailsForm fctreg = new FacultyDetailsForm("back");
                fctreg.getPrevious();
                fctreg.setVisible(true);
            } else {
                FacultyDetailsForm fctreg = new FacultyDetailsForm("edit");
                fctreg.getPrevious();
                fctreg.setVisible(true);
            }
        }
        this.dispose();
        
    }
    
    private void keySave(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keySave
        keyAction(evt,"submit");
    }//GEN-LAST:event_keySave
    
    private void keyBack(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyBack
        keyAction(evt,"back");
    }//GEN-LAST:event_keyBack
    void keyAction(java.awt.event.KeyEvent evt, String Button) {
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            if (Button.equalsIgnoreCase("cancel")) {
                int i=DialogBox.dialog.confirmDialog("All the details will get lost.. Do you want to cancel ??");
             if(i==0)
             {
                 this.dispose();
             }
             else if(i==1){}
             else if(i==2){}
            } 
            else if (Button.equalsIgnoreCase("submit")) {
                submit();
            }
            else if (Button.equalsIgnoreCase("back")) {
                back();
            }
            else{
            submit();
            }
        }
        if (key == KeyEvent.VK_ESCAPE) {    
             int i=DialogBox.dialog.confirmDialog("All the details will get lost.. Do you want to cancel ??");
             if(i==0)
             {
                 this.dispose();
             }
             else if(i==1){}
             else if(i==2){}
            }
    }
    private void keyCancel(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyCancel
        keyAction(evt,"cancel");
        // TODO add your handling code here:
    }//GEN-LAST:event_keyCancel
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JButton back;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel dept;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phoneno;
    private javax.swing.JPanel photoPanel;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel post;
    private javax.swing.JLabel registeredat;
    private javax.swing.JButton save;
    private javax.swing.JLabel validUpto;
    // End of variables declaration//GEN-END:variables
}
