

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;

/**
 *
 * @author Achyut
 */
public class GenerateReport extends javax.swing.JFrame {

    String formType = "";

    /**
     * Creates new form GenerateReport
     */
    public GenerateReport(String action) {
        initComponents();
        setLocationRelativeTo(null);
        generateall.setSelected(true);
        formType = action;
        this.from.disable();
        this.to.disable();
        this.lblfrom.disable();
        this.lblto.disable();
    }

    private void submit() {
        ResultSet rs=null;
        if (!this.id.getText().isEmpty() && this.name.getText().isEmpty())  {
            display();
                  }
        else if(!this.id.getText().isEmpty() && !this.name.getText().isEmpty()){
                    rs=AbstractPerson.ab.IfPersonExists(this.id.getText(),this.name.getText());
                  if(rs!=null){
                      display();
                    }
                else
                {
                    DialogBox.dialog.errorDialog("Person with such details doesn't exist");
                  }
            
        }
        else if (this.id.getText().isEmpty() && !this.name.getText().isEmpty()) {
                if(formType.equalsIgnoreCase("blacklistdisplay")){
                DuplicateName dn = new DuplicateName(this.name.getText(),"blacklistdisplay");
                dn.setVisible(true);
               }
               else if(formType.equalsIgnoreCase("checkinout")){
                DuplicateName dn = new DuplicateName(this.name.getText(),"checkinout");
                dn.setVisible(true);
               }
               else{
                DuplicateName dn = new DuplicateName(this.name.getText(),"all");
                dn.setVisible(true);
               }
        }
        else{
        DialogBox.dialog.errorDialog("Please enter ID/Name");
        }
    }

    void display(){
          if (Validation.val.validateID(this.id.getText()) == true) {
                if (formType.equalsIgnoreCase("blacklistdisplay")) {
                    if (this.generateall.isSelected() == true) {
                        BlackListMainReport br = new BlackListMainReport(this.id.getText(), this.from.getText(), this.to.getText(),true);
                        br.setVisible(true);
                    } else {
                        BlackListMainReport br = new BlackListMainReport(this.id.getText(), this.from.getText(), this.to.getText(),false);
                        br.setVisible(true);                    }
                } else if (formType.equalsIgnoreCase("checkinout")) {
                    if (this.generateall.isSelected() == true) {
                        CheckincheckOutReport cr = new CheckincheckOutReport(this.id.getText(), this.from.getText(), this.to.getText(),true);
                        cr.setVisible(true);
                    } else {
                        CheckincheckOutReport cr = new CheckincheckOutReport(this.id.getText(), this.from.getText(), this.to.getText(),false);
                        cr.setVisible(true);
                    }
                }
            }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        generateall = new javax.swing.JCheckBox();
        from = new javax.swing.JTextField();
        lblfrom = new javax.swing.JLabel();
        to = new javax.swing.JTextField();
        lblto = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(": : Generate Report : :");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 2, true), "Generate Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("ID/ Roll No:");

        name.setBackground(java.awt.SystemColor.info);
        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameKeyPressed(evt);
            }
        });

        id.setBackground(java.awt.SystemColor.info);
        id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idKeyPressed(evt);
            }
        });

        generateall.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        generateall.setText("Generate all");
        generateall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateallgenerateAll(evt);
            }
        });
        generateall.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                generateallKeyPressed(evt);
            }
        });

        from.setBackground(java.awt.SystemColor.info);
        from.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        from.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fromKeyPressed(evt);
            }
        });

        lblfrom.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblfrom.setText("From:");

        to.setBackground(java.awt.SystemColor.info);
        to.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toActionPerformed(evt);
            }
        });
        to.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                toKeyPressed(evt);
            }
        });

        lblto.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblto.setText("To:");

        submitButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        submitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/checkin.png"))); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        submitButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                submitButtonkeySubmit(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Name :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(id)
                                    .addComponent(name)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(generateall)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblfrom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(lblto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateall)
                    .addComponent(lblfrom)
                    .addComponent(lblto)
                    .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateallgenerateAll(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateallgenerateAll
        if (generateall.isSelected() == true) {
            this.from.disable();
            this.to.disable();
            this.lblfrom.disable();
            this.lblto.disable();
        } else if (generateall.isSelected() == false) {
            this.from.enable();
            this.to.enable();
            this.lblfrom.enable();
            this.lblto.enable();
            this.from.setText(TimeDate.time.timestampToFullDate(System.currentTimeMillis()-(7*24*60*60*1000)));
            this.to.setText(TimeDate.time.timestampToFullDate(System.currentTimeMillis()));
        }
    }//GEN-LAST:event_generateallgenerateAll

    private void toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        submit();
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonActionPerformed

    private void submitButtonkeySubmit(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_submitButtonkeySubmit
       keyAction(evt);     // TODO add your handling code here: // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonkeySubmit

    void keyAction(java.awt.event.KeyEvent evt){
        int key = evt.getKeyCode();
        if(key == KeyEvent.VK_ENTER){
            submit();
        }
        if(key == KeyEvent.VK_ESCAPE){
            this.dispose();
          }
        }
    private void idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyPressed
        keyAction(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_idKeyPressed

    private void nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyPressed
        keyAction(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_nameKeyPressed

    private void generateallKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_generateallKeyPressed
        keyAction(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_generateallKeyPressed

    private void fromKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fromKeyPressed

        keyAction(evt);// TODO add your handling code here:
    }//GEN-LAST:event_fromKeyPressed

    private void toKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_toKeyPressed

        keyAction(evt);// TODO add your handling code here:
    }//GEN-LAST:event_toKeyPressed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField from;
    private javax.swing.JCheckBox generateall;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblfrom;
    private javax.swing.JLabel lblto;
    private javax.swing.JTextField name;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField to;
    // End of variables declaration//GEN-END:variables
}
