/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * guestDetailsForm.java
 *
 * Created on Jan 18, 2012, 1:43:41 AM
 */
package test;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/**
 *
 * @author Administrator
 */
public class GuestDetailsForm extends javax.swing.JFrame {
    String action="";
    int tempID;
    public GuestDetailsForm() {
        initComponents();
        setLocationRelativeTo(null);
        Thread thd = new Thread(){
            @Override
        public void run(){
        Component video;
        video = Webcam.cam.getVideo();
        if(video != null){
            video.setSize(photo.getWidth(), photo.getHeight());
        } else {
            video = new Component() {};
        }
        photo.add(video,BorderLayout.CENTER);
        if(Webcam.cam.isLoaded() != false){
        Webcam.cam.startCam();
        }
        }
        };
        thd.start();
        this.photoPanel.hide();
        this.editPic.hide();
        tempID = Guest.gst.generateGuestID();
        this.guestId.setText("GST-"+tempID);
        int valid = Integer.parseInt(TimeDate.time.timestampToFullDate(System.currentTimeMillis()).substring(0, 4));
        guestValidUpto.setText(Integer.toString(valid+1));
    }
    
    public GuestDetailsForm(String type){
            //getPrevious();
        action=type;
        initComponents();
        setLocationRelativeTo(null);          
        this.photo.hide();
        this.capture.hide();
        if(Guest.gst.image != null){
                ImageIcon thumbnailIcon = new ImageIcon(Utilities.util.rescaleImage(Guest.gst.image,this.photoPanel.getWidth(),this.photoPanel.getHeight()));
                this.pic.setIcon(thumbnailIcon);
            }
     tempID = Guest.gst.generateGuestID();
     this.guestId.setText("GST-"+tempID);   
    }
    private void refreshID(){
        tempID = tempID + 1;
        this.guestId.setText("GST-"+tempID);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        guestId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        guestAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        guestName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        guestPhone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        guestRef = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        guestOccupation = new javax.swing.JTextField();
        guestValidUpto = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        reset = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        photo = new javax.swing.JPanel();
        capture = new javax.swing.JToggleButton();
        photoPanel = new javax.swing.JPanel();
        pic = new javax.swing.JLabel();
        editPic = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(": : Guest Registration : :");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                windowclosed(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                windowactivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Guest Registeration Form");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        guestId.setBackground(new java.awt.Color(255, 255, 225));
        guestId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guestId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        guestId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                guestIdKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Valid Upto:");

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/button_cancel.png"))); // NOI18N
        cancel.setText("cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        cancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cancelKeyPressed(evt);
            }
        });

        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/checkin.png"))); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        submit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                submitKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Refernce by:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Occupation:");

        guestAddress.setBackground(new java.awt.Color(255, 255, 225));
        guestAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guestAddress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        guestAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestAddressActionPerformed(evt);
            }
        });
        guestAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                guestAddressKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Address:");

        guestName.setBackground(new java.awt.Color(255, 255, 225));
        guestName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guestName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        guestName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                guestNameKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Phone no:");

        guestPhone.setBackground(new java.awt.Color(255, 255, 225));
        guestPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guestPhone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        guestPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                guestPhoneKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("ID:");

        guestRef.setBackground(new java.awt.Color(255, 255, 225));
        guestRef.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guestRef.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        guestRef.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                guestRefKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Name:");

        guestOccupation.setBackground(new java.awt.Color(255, 255, 225));
        guestOccupation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guestOccupation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        guestOccupation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                guestOccupationKeyPressed(evt);
            }
        });

        guestValidUpto.setBackground(new java.awt.Color(255, 255, 225));
        guestValidUpto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guestValidUpto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        guestValidUpto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                guestValidUptoKeyPressed(evt);
            }
        });

        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/refresh.png"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        reset.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                resetKeyPressed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/24/refresh.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(submit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(guestOccupation)
                                    .addComponent(guestPhone, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(guestName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(guestAddress, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(guestRef, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(guestValidUpto, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(guestId, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11)))))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(guestId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guestName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(guestAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(guestPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(guestRef, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guestOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(guestValidUpto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        photo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout photoLayout = new javax.swing.GroupLayout(photo);
        photo.setLayout(photoLayout);
        photoLayout.setHorizontalGroup(
            photoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );
        photoLayout.setVerticalGroup(
            photoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );

        jPanel2.add(photo);

        capture.setText("Take Snapshot");
        capture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                captureActionPerformed(evt);
            }
        });
        capture.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                captureKeyPressed(evt);
            }
        });
        jPanel2.add(capture);

        photoPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout photoPanelLayout = new javax.swing.GroupLayout(photoPanel);
        photoPanel.setLayout(photoPanelLayout);
        photoPanelLayout.setHorizontalGroup(
            photoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        );
        photoPanelLayout.setVerticalGroup(
            photoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );

        jPanel2.add(photoPanel);

        editPic.setText("Edit Pic");
        editPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPicActionPerformed(evt);
            }
        });
        jPanel2.add(editPic);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/64/guest.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        submit();
      
    }//GEN-LAST:event_submitActionPerformed

    void submit(){
    if(putGuestInfo()){
          if(action.equalsIgnoreCase("edit")){
              GuestDetails gstDetail = new GuestDetails("edit");
              gstDetail.setVisible(true);
            }
          if(action.equalsIgnoreCase("delete")){
              GuestDetails gstDetail = new GuestDetails("delete");
              gstDetail.setVisible(true);
            }
          else if(action.equalsIgnoreCase("") || action.equalsIgnoreCase("back")){
              GuestDetails gstDetail = new GuestDetails(1);
            gstDetail.setVisible(true);
                }
                     this.dispose();
            }
    }
        boolean putGuestInfo(){
    if(Validation.val.validateGuestInfo(this.guestId.getText(),this.guestName.getText(),this.guestAddress.getText(),this.guestPhone.getText(),this.guestRef.getText(),this.guestOccupation.getText(),this.guestValidUpto.getText()) == true){            
        Guest.gst.name = this.guestName.getText();
        Guest.gst.id = this.guestId.getText();
        Guest.gst.address = this.guestAddress.getText();
        Guest.gst.phone = this.guestPhone.getText();
        Guest.gst.reference = this.guestRef.getText();
        Guest.gst.occupation =this.guestOccupation.getText();
        Guest.gst.validUpto = Integer.parseInt(this.guestValidUpto.getText());
        
        if(!action.equalsIgnoreCase("edit")){
        Guest.gst.addtimestamp=TimeDate.time.timestampToFullDate(AbstractPerson.ab.currentTimeStamp());
        Guest.gst.addedby=Session.s1.sessionUser;
        }
        Guest.gst.password = this.guestId.getText();
        
        return true;
        }
    else 
        return false;
    }
    void resetItems(){
        //enableItems();        
                this.guestName.setText("");
                this.guestPhone.setText("");
                this.guestAddress.setText("");
                this.guestRef.setText("");
                this.guestOccupation.setText("");
    }
     void getPrevious()
     {
           this.guestId.setText(Guest.gst.id);
                this.guestName.setText(Guest.gst.name);
                this.guestPhone.setText(Guest.gst.phone);
                this.guestAddress.setText(Guest.gst.address);
                this.guestRef.setText(Guest.gst.reference);
                this.guestOccupation.setText(Guest.gst.occupation);
                this.guestValidUpto.setText(((Integer)Guest.gst.validUpto).toString());    
     }

    
    
    private void guestAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guestAddressActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed

        if(Webcam.cam.isLoaded()!=false){
            Webcam.cam.stopCam();
        }
        this.dispose();
     //   clerkFormMain.clerk.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        resetItems();        // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void windowactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowactivated
        // TODO add your handling code here:
    }//GEN-LAST:event_windowactivated

    private void captureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_captureActionPerformed

         if(capture.isSelected()){
             
           Webcam.cam.captureImage();
           BufferedImage bi = Webcam.cam.getBufferedImage();
           Guest.gst.image = bi;
           Guest.gst.fingerprint = bi;
           Webcam.cam.stopCam();
        }
        else if(!capture.isSelected())
        {
            Webcam.cam.startCam();
        }
         // TODO add your handling code here:
    }//GEN-LAST:event_captureActionPerformed

    private void windowclosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowclosed
         if(Webcam.cam.isLoaded()!=false){
            Webcam.cam.closeCam();
        }
    }//GEN-LAST:event_windowclosed

    private void editPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPicActionPerformed

        WebcamTest t = new WebcamTest("guest");
        t.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_editPicActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked

        refreshID();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    void keyAction(java.awt.event.KeyEvent evt, String Button) {
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            if (Button.equalsIgnoreCase("cancel")) {
                int i=DialogBox.dialog.confirmDialog("All the details will get lost.. Do you want to cancel ??");
             if(i==0)
             {
                 this.dispose();
             }
             else if(i==1){}
             else if(i==2){}
            } 
            else if (Button.equalsIgnoreCase("submit")) {
                submit();
            }
            else if (Button.equalsIgnoreCase("reset")) {
                resetItems();
            }
            else{
            submit();
            }
        }
        if (key == KeyEvent.VK_ESCAPE) {    
             int i=DialogBox.dialog.confirmDialog("All the details will get lost.. Do you want to cancel ??");
             if(i==0)
             {
                 this.dispose();
             }
             else if(i==1){}
             else if(i==2){}
            }
    }
    private void guestIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_guestIdKeyPressed

     int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        guestName.requestFocus();
        }
        else{
        keyAction(evt,"submit");
        }
    }//GEN-LAST:event_guestIdKeyPressed

    private void guestAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_guestAddressKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        guestPhone.requestFocus();
        }
        else{
        keyAction(evt,"submit");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_guestAddressKeyPressed

    private void guestNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_guestNameKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        guestAddress.requestFocus();
        }
        else{
        keyAction(evt,"submit");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_guestNameKeyPressed

    private void guestPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_guestPhoneKeyPressed

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        guestRef.requestFocus();
        }
        else{
        keyAction(evt,"submit");
        }// TODO add your handling code here:
    }//GEN-LAST:event_guestPhoneKeyPressed

    private void guestRefKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_guestRefKeyPressed

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        guestOccupation.requestFocus();
        }
        else{
        keyAction(evt,"submit");
        }// TODO add your handling code here:
    }//GEN-LAST:event_guestRefKeyPressed

    private void guestOccupationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_guestOccupationKeyPressed

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        guestValidUpto.requestFocus();
        }
        else{
        keyAction(evt,"submit");
        }// TODO add your handling code here:
    }//GEN-LAST:event_guestOccupationKeyPressed

    private void guestValidUptoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_guestValidUptoKeyPressed

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        capture.requestFocus();
        }
        else{
        keyAction(evt,"submit");
        }// TODO add your handling code here:
    }//GEN-LAST:event_guestValidUptoKeyPressed

    private void submitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_submitKeyPressed

        keyAction(evt,"submit");
    }//GEN-LAST:event_submitKeyPressed

    private void resetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resetKeyPressed
    keyAction(evt,"reset");
    }//GEN-LAST:event_resetKeyPressed

    private void cancelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cancelKeyPressed
        keyAction(evt,"cancel");
         // TODO add your handling code here:
    }//GEN-LAST:event_cancelKeyPressed

    private void captureKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_captureKeyPressed
int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        submit.requestFocus();
        }
        else{
        keyAction(evt,"reset");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_captureKeyPressed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JToggleButton capture;
    private javax.swing.JButton editPic;
    private javax.swing.JTextField guestAddress;
    private javax.swing.JTextField guestId;
    private javax.swing.JTextField guestName;
    private javax.swing.JTextField guestOccupation;
    private javax.swing.JTextField guestPhone;
    private javax.swing.JTextField guestRef;
    private javax.swing.JTextField guestValidUpto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel photo;
    private javax.swing.JPanel photoPanel;
    private javax.swing.JLabel pic;
    private javax.swing.JButton reset;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
