/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.io.IOException;

/**
 *
 * @author Achyut
 */
public class Init4 extends javax.swing.JFrame {

    /**
     * Creates new form Init4
     */
    public Init4() {
        initComponents();
        setLocationRelativeTo(null);
        setValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        masterDbPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        masterDbType = new javax.swing.JLabel();
        masterIp = new javax.swing.JLabel();
        masterDbName = new javax.swing.JLabel();
        masterDbUsername = new javax.swing.JLabel();
        masterPort = new javax.swing.JLabel();
        masterConn = new javax.swing.JLabel();
        masterPassword = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        useMasterSSL = new javax.swing.JLabel();
        masterDbPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        localDbType = new javax.swing.JLabel();
        localIpAddress = new javax.swing.JLabel();
        localDbName = new javax.swing.JLabel();
        localDbUsername = new javax.swing.JLabel();
        localDbPort = new javax.swing.JLabel();
        localDbConn = new javax.swing.JLabel();
        localDbPassword = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        useLocalSSL = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        masterDbPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        defaultWebcam = new javax.swing.JLabel();
        defaultFingerPrint = new javax.swing.JLabel();
        masterDbPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        rootUsername = new javax.swing.JLabel();
        rootPassword = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        defaultLookAndFeel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        priority = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(": : Initialize : :");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/apely_logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("College", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("APELEY DISTRIBUTED AUTHENTICATION SYSTEMS");

        masterDbPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Master Database Configuration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Database Type:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Ip Address:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Port No:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Username:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Password:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Conn String:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Database Name: ");

        masterDbType.setText("jLabel18");

        masterIp.setText("jLabel18");

        masterDbName.setText("jLabel18");

        masterDbUsername.setText("jLabel18");

        masterPort.setText("jLabel18");

        masterConn.setText("jLabel18");

        masterPassword.setText("jLabel18");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Use Master SSL:");

        useMasterSSL.setText("jLabel18");

        javax.swing.GroupLayout masterDbPanelLayout = new javax.swing.GroupLayout(masterDbPanel);
        masterDbPanel.setLayout(masterDbPanelLayout);
        masterDbPanelLayout.setHorizontalGroup(
            masterDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masterDbPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(masterDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(masterDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(masterIp)
                    .addComponent(masterDbName)
                    .addComponent(masterDbUsername)
                    .addComponent(masterDbType))
                .addGap(164, 164, 164)
                .addGroup(masterDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(masterDbPanelLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(useMasterSSL))
                    .addGroup(masterDbPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(masterConn))
                    .addGroup(masterDbPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(masterPassword))
                    .addGroup(masterDbPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addComponent(masterPort)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        masterDbPanelLayout.setVerticalGroup(
            masterDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masterDbPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(masterDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(masterDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(useMasterSSL))
                    .addGroup(masterDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(masterDbType)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(masterDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(masterIp)
                    .addComponent(masterPort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(masterDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(masterDbName)
                    .addComponent(masterConn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(masterDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(masterDbUsername)
                    .addComponent(masterPassword))
                .addGap(55, 55, 55))
        );

        masterDbPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Local Database Configuration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Database Type:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Ip Address:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Port No:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Username:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Password:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Conn String:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Database Name: ");

        localDbType.setText("jLabel18");

        localIpAddress.setText("jLabel18");

        localDbName.setText("jLabel18");

        localDbUsername.setText("jLabel18");

        localDbPort.setText("jLabel18");

        localDbConn.setText("jLabel18");

        localDbPassword.setText("jLabel18");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Use Local SSL:");

        useLocalSSL.setText("jLabel18");

        javax.swing.GroupLayout masterDbPanel1Layout = new javax.swing.GroupLayout(masterDbPanel1);
        masterDbPanel1.setLayout(masterDbPanel1Layout);
        masterDbPanel1Layout.setHorizontalGroup(
            masterDbPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masterDbPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(masterDbPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(masterDbPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(localIpAddress)
                    .addComponent(localDbName)
                    .addComponent(localDbUsername)
                    .addComponent(localDbType))
                .addGap(165, 165, 165)
                .addGroup(masterDbPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(masterDbPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(useLocalSSL))
                    .addGroup(masterDbPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(35, 35, 35)
                        .addComponent(localDbPort))
                    .addGroup(masterDbPanel1Layout.createSequentialGroup()
                        .addGroup(masterDbPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(masterDbPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(localDbPassword)
                            .addComponent(localDbConn))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        masterDbPanel1Layout.setVerticalGroup(
            masterDbPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masterDbPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(masterDbPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(masterDbPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(localDbType)
                        .addComponent(useLocalSSL)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(masterDbPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(localIpAddress)
                    .addComponent(localDbPort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(masterDbPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(localDbName)
                    .addComponent(localDbConn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(masterDbPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(localDbUsername)
                    .addComponent(localDbPassword))
                .addGap(55, 55, 55))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Write Configuration");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancel");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(104, 104, 104)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("Are These Configuration Correct ????");

        masterDbPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Default Capture Devices", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Default Webcam: ");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Default Fingerprint Reader: ");

        defaultWebcam.setText("jLabel18");

        defaultFingerPrint.setText("jLabel18");

        javax.swing.GroupLayout masterDbPanel2Layout = new javax.swing.GroupLayout(masterDbPanel2);
        masterDbPanel2.setLayout(masterDbPanel2Layout);
        masterDbPanel2Layout.setHorizontalGroup(
            masterDbPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masterDbPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(masterDbPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(masterDbPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(66, 66, 66)
                        .addComponent(defaultWebcam))
                    .addGroup(masterDbPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(defaultFingerPrint)))
                .addContainerGap(378, Short.MAX_VALUE))
        );
        masterDbPanel2Layout.setVerticalGroup(
            masterDbPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masterDbPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(masterDbPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(defaultWebcam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(masterDbPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(defaultFingerPrint))
                .addContainerGap())
        );

        masterDbPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Root Username and Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Username:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Password:");

        rootUsername.setText("jLabel18");

        rootPassword.setText("jLabel18");

        javax.swing.GroupLayout masterDbPanel3Layout = new javax.swing.GroupLayout(masterDbPanel3);
        masterDbPanel3.setLayout(masterDbPanel3Layout);
        masterDbPanel3Layout.setHorizontalGroup(
            masterDbPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masterDbPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(rootUsername)
                .addGap(189, 189, 189)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rootPassword)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        masterDbPanel3Layout.setVerticalGroup(
            masterDbPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masterDbPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(masterDbPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(rootUsername)
                    .addComponent(rootPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Default Look and Feel: ");

        defaultLookAndFeel.setText("jLabel18");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Priority:");

        priority.setText("jLabel18");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(masterDbPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(masterDbPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(masterDbPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator1)
                                    .addComponent(jSeparator2)))
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(masterDbPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(defaultLookAndFeel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(34, 34, 34)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(priority)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(priority)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(masterDbPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(masterDbPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(masterDbPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(masterDbPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(defaultLookAndFeel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Init3 in3 = new Init3();
        in3.getPrevious();
        this.dispose();
        in3.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setValuesToFile();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void setValuesToFile() {
        try {
            ReadConfigFile.conf.writeConfig("useMasterDb","true");
            ReadConfigFile.conf.writeConfig("useLocalDb", ReadConfigFile.conf.useLocalDb);
            ReadConfigFile.conf.writeConfig("dbPriority", ReadConfigFile.conf.dbPriority);
            ReadConfigFile.conf.writeConfig("masterDbType", ReadConfigFile.conf.masterDbType);
            if (ReadConfigFile.conf.useMasterSSL == true) {
                ReadConfigFile.conf.writeConfig("useMasterSSL", "true");
            } else {
                ReadConfigFile.conf.writeConfig("useMasterSSL", "false");
            }
            ReadConfigFile.conf.writeConfig("masterDbIp", ReadConfigFile.conf.masterDbIp);
            ReadConfigFile.conf.writeConfig("masterDbPort", ReadConfigFile.conf.masterDbPort);
            ReadConfigFile.conf.writeConfig("masterDbName", ReadConfigFile.conf.masterDbName);
            ReadConfigFile.conf.writeConfig("masterConnStr", ReadConfigFile.conf.masterConnStr);
            ReadConfigFile.conf.writeConfig("masterUsername", ReadConfigFile.conf.masterUsername);
            ReadConfigFile.conf.writeConfig("masterPassword", ReadConfigFile.conf.masterPassword);

            ReadConfigFile.conf.writeConfig("localDbType", ReadConfigFile.conf.localDbType);
            if (ReadConfigFile.conf.useLocalSSL == true) {
                ReadConfigFile.conf.writeConfig("useLocalSSL", "true");
            } else {
                ReadConfigFile.conf.writeConfig("useLocalSSL", "false");
            }
            ReadConfigFile.conf.writeConfig("localDbIp", ReadConfigFile.conf.localDbIp);
            ReadConfigFile.conf.writeConfig("localDbPort", ReadConfigFile.conf.localDbPort);
            ReadConfigFile.conf.writeConfig("localDbName", ReadConfigFile.conf.localDbName);
            ReadConfigFile.conf.writeConfig("localConnStr", ReadConfigFile.conf.localConnStr);
            ReadConfigFile.conf.writeConfig("localUsername", ReadConfigFile.conf.localUsername);
            ReadConfigFile.conf.writeConfig("localPassword", ReadConfigFile.conf.localPassword);
            // root password
            //root username
            ReadConfigFile.conf.writeConfig("defaultWebcam",ReadConfigFile.conf.defaultWebcam);
            ReadConfigFile.conf.writeConfig("defaultFingerprint",ReadConfigFile.conf.defaultFingerprint);
            ReadConfigFile.conf.writeConfig("defaultLookAndFeel",ReadConfigFile.conf.defaultLookAndFeel);
            DialogBox.dialog.successDialog("Configuration File Successfully Written!!!!! \n Please restart the software.");
            this.dispose();
            
        } catch (IOException ae) {
            Log.log.writeErrorLog("Error!!!! Configuration File cannot be written.."+ae.getMessage(), "Init4", "setValuesToFile");
        }
    }

    void setValues() {
        this.masterDbType.setText(ReadConfigFile.conf.masterDbType);
        this.masterIp.setText(ReadConfigFile.conf.masterDbIp);
        this.masterPort.setText(ReadConfigFile.conf.masterDbPort);
        this.masterDbName.setText(ReadConfigFile.conf.masterDbName);
        this.masterConn.setText(ReadConfigFile.conf.masterConnStr);
        this.masterDbUsername.setText(ReadConfigFile.conf.masterUsername);
        this.masterPassword.setText(ReadConfigFile.conf.masterPassword);
        if (ReadConfigFile.conf.useMasterSSL == true) {
            this.useMasterSSL.setText("True");
        } else {
            this.useMasterSSL.setText("False");
        }
        if (ReadConfigFile.conf.useLocalSSL == true) {
            this.useLocalSSL.setText("True");
        } else {
            this.useLocalSSL.setText("False");
        }

        this.priority.setText(ReadConfigFile.conf.dbPriority);
        this.localDbType.setText(ReadConfigFile.conf.localDbType);
        this.localIpAddress.setText(ReadConfigFile.conf.localDbIp);
        this.localDbPort.setText(ReadConfigFile.conf.localDbPort);
        this.localDbName.setText(ReadConfigFile.conf.localDbName);
        this.localDbConn.setText(ReadConfigFile.conf.localConnStr);
        this.localDbUsername.setText(ReadConfigFile.conf.localUsername);
        this.localDbPassword.setText(ReadConfigFile.conf.localPassword);

        this.rootUsername.setText(ReadConfigFile.conf.rootUsername);
        this.rootPassword.setText(ReadConfigFile.conf.rootPassword);

        this.defaultWebcam.setText(ReadConfigFile.conf.defaultWebcam);
        this.defaultFingerPrint.setText(ReadConfigFile.conf.defaultFingerprint);
        this.defaultLookAndFeel.setText(ReadConfigFile.conf.defaultLookAndFeel);

    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel defaultFingerPrint;
    private javax.swing.JLabel defaultLookAndFeel;
    private javax.swing.JLabel defaultWebcam;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel localDbConn;
    private javax.swing.JLabel localDbName;
    private javax.swing.JLabel localDbPassword;
    private javax.swing.JLabel localDbPort;
    private javax.swing.JLabel localDbType;
    private javax.swing.JLabel localDbUsername;
    private javax.swing.JLabel localIpAddress;
    private javax.swing.JLabel masterConn;
    private javax.swing.JLabel masterDbName;
    private javax.swing.JPanel masterDbPanel;
    private javax.swing.JPanel masterDbPanel1;
    private javax.swing.JPanel masterDbPanel2;
    private javax.swing.JPanel masterDbPanel3;
    private javax.swing.JLabel masterDbType;
    private javax.swing.JLabel masterDbUsername;
    private javax.swing.JLabel masterIp;
    private javax.swing.JLabel masterPassword;
    private javax.swing.JLabel masterPort;
    private javax.swing.JLabel priority;
    private javax.swing.JLabel rootPassword;
    private javax.swing.JLabel rootUsername;
    private javax.swing.JLabel useLocalSSL;
    private javax.swing.JLabel useMasterSSL;
    // End of variables declaration//GEN-END:variables
}
