/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * studentRegistration.java
 *
 * Created on Jan 20, 2012, 3:53:17 PM
 */
package test;

/**
 *
 * @author Achyut
 */

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

public class StudentRegistration extends javax.swing.JFrame {
        
    /** Creates new form studentRegistration */
    String action="";
    public StudentRegistration() {
        initComponents();
        setLocationRelativeTo(null);
        Thread thd = new Thread(){
            @Override
        public void run(){
        Component video;
        video = Webcam.cam.getVideo();
        if(video != null){
            video.setSize(photo.getWidth(), photo.getHeight());
        } else {
            video = new Component() {};
        }
        photo.add(video,BorderLayout.CENTER);
        if(Webcam.cam.isLoaded() !=false){
        Webcam.cam.startCam();
        }
        }
        };
        thd.start();
        this.photoPanel.hide();
        this.editPic.hide();
    }
    
    public StudentRegistration(String type){
            //getPrevious();
        action=type;
        initComponents();
          setLocationRelativeTo(null);
        this.photo.hide();
        this.capture.hide();
        if(Student.std.image != null){
         ImageIcon thumbnailIcon = new ImageIcon(Utilities.util.rescaleImage(Student.std.image,this.photoPanel.getWidth(),this.photoPanel.getHeight()));
         this.pic.setIcon(thumbnailIcon);
            }
        
    }
  /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        mainlbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        photo = new javax.swing.JPanel();
        capture = new javax.swing.JToggleButton();
        photoPanel = new javax.swing.JPanel();
        pic = new javax.swing.JLabel();
        editPic = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        validUpto = new javax.swing.JTextField();
        validupto = new javax.swing.JLabel();
        macadd2 = new javax.swing.JLabel();
        macAdd2 = new javax.swing.JTextField();
        macAdd1 = new javax.swing.JTextField();
        macadd1 = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        addrss = new javax.swing.JTextField();
        phonNo = new javax.swing.JTextField();
        phonno = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        branch = new javax.swing.JLabel();
        year1 = new javax.swing.JComboBox();
        Branch = new javax.swing.JComboBox();
        fullName = new javax.swing.JTextField();
        rollNo = new javax.swing.JTextField();
        rollno = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(": : Student Registration : :");
        setName("Student Registration");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                StudentRegistration.this.windowClosed(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                StudentRegistration.this.windowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mainlbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        mainlbl.setForeground(new java.awt.Color(0, 0, 102));
        mainlbl.setText("Student Registration Form");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/64/student.png"))); // NOI18N

        photo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout photoLayout = new javax.swing.GroupLayout(photo);
        photo.setLayout(photoLayout);
        photoLayout.setHorizontalGroup(
            photoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );
        photoLayout.setVerticalGroup(
            photoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );

        jPanel3.add(photo);

        capture.setText("Take Snapshot");
        capture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                captureActionPerformed(evt);
            }
        });
        capture.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                captureKeyPressed(evt);
            }
        });
        jPanel3.add(capture);

        photoPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout photoPanelLayout = new javax.swing.GroupLayout(photoPanel);
        photoPanel.setLayout(photoPanelLayout);
        photoPanelLayout.setHorizontalGroup(
            photoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        );
        photoPanelLayout.setVerticalGroup(
            photoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );

        jPanel3.add(photoPanel);

        editPic.setText("Edit Pic");
        editPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPicActionPerformed(evt);
            }
        });
        jPanel3.add(editPic);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        validUpto.setBackground(new java.awt.Color(255, 255, 225));
        validUpto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        validUpto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        validUpto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validUptoKeyPressed(evt);
            }
        });

        validupto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        validupto.setForeground(new java.awt.Color(0, 0, 255));
        validupto.setText("Valid Upto:");

        macadd2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        macadd2.setForeground(new java.awt.Color(0, 0, 255));
        macadd2.setText("Mac Address2:");

        macAdd2.setBackground(new java.awt.Color(255, 255, 225));
        macAdd2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        macAdd2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        macAdd2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                macAdd2KeyPressed(evt);
            }
        });

        macAdd1.setBackground(new java.awt.Color(255, 255, 225));
        macAdd1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        macAdd1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        macAdd1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                macAdd1KeyPressed(evt);
            }
        });

        macadd1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        macadd1.setForeground(new java.awt.Color(0, 0, 255));
        macadd1.setText("Mac Address1:");

        address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        address.setForeground(new java.awt.Color(0, 0, 255));
        address.setText("Address:");

        addrss.setBackground(new java.awt.Color(255, 255, 225));
        addrss.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addrss.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        addrss.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addrssKeyPressed(evt);
            }
        });

        phonNo.setBackground(new java.awt.Color(255, 255, 225));
        phonNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phonNo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        phonNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phonNoKeyPressed(evt);
            }
        });

        phonno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phonno.setForeground(new java.awt.Color(0, 0, 255));
        phonno.setText("Phone no:");

        year.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        year.setForeground(new java.awt.Color(0, 0, 255));
        year.setText("Batch:");

        branch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        branch.setForeground(new java.awt.Color(0, 0, 255));
        branch.setText("Branch:");

        year1.setBackground(new java.awt.Color(255, 255, 225));
        year1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        year1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));
        year1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                batchSelect(evt);
            }
        });
        year1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                year1KeyPressed(evt);
            }
        });

        Branch.setBackground(new java.awt.Color(255, 255, 225));
        Branch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Branch.setMaximumRowCount(9);
        Branch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Computer Engg.\t", "Information Technology\t", "Electronics and communication\t", "Electrical", "Civil", "Mechanical", "Industrial" }));
        Branch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Branch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BranchKeyPressed(evt);
            }
        });

        fullName.setBackground(new java.awt.Color(255, 255, 225));
        fullName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fullName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        fullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullNameActionPerformed(evt);
            }
        });
        fullName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fullNameKeyPressed(evt);
            }
        });

        rollNo.setBackground(new java.awt.Color(255, 255, 225));
        rollNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rollNo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        rollNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rollNoKeyPressed(evt);
            }
        });

        rollno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rollno.setForeground(new java.awt.Color(0, 0, 255));
        rollno.setText("Roll No:");

        fullname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fullname.setForeground(new java.awt.Color(0, 0, 255));
        fullname.setText("Full Name:");

        submit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/checkin.png"))); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        submit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                submitKeyPressed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/refresh.png"))); // NOI18N
        delete.setText("reset");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        delete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deleteKeyPressed(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/button_cancel.png"))); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        cancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cancelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(rollno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(branch)
                            .addComponent(year)
                            .addComponent(phonno)
                            .addComponent(address)
                            .addComponent(macadd1)
                            .addComponent(macadd2)
                            .addComponent(validupto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(macAdd2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(macAdd1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addrss, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(phonNo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Branch, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rollNo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fullName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(year1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(validUpto, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(submit)
                .addGap(31, 31, 31)
                .addComponent(delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancel)
                .addGap(6, 6, 6))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rollno)
                    .addComponent(rollNo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Branch, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(branch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phonNo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addrss, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(macAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(macadd1))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(macAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(macadd2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validUpto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validupto))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(35, 35, 35)
                        .addComponent(mainlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(mainlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_fullNameActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
     submit();
        // TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
           if(Webcam.cam.isLoaded()!=false){
            Webcam.cam.stopCam();
        }
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        resetItems();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void batchSelect(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_batchSelect
  // System.out.print(Integer.parseInt(this.year1.getSelectedItem().toString())+4);e
        if(year1.getSelectedIndex()!=0)
        validUpto.setText(((Integer)(Integer.parseInt(this.year1.getSelectedItem().toString())+4)).toString());
    }//GEN-LAST:event_batchSelect

    private void windowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowActivated
       
    }//GEN-LAST:event_windowActivated

    private void windowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosed
                   if(Webcam.cam.isLoaded()!=false){
            Webcam.cam.closeCam();
        }

    }//GEN-LAST:event_windowClosed

    private void captureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_captureActionPerformed

        if (capture.isSelected()) {
            Webcam.cam.captureImage();
            BufferedImage bi = Webcam.cam.getBufferedImage();
            Student.std.image = bi;
            Student.std.fingerprint = bi;
            Webcam.cam.stopCam();
        } else if (!capture.isSelected()) {
            Webcam.cam.startCam();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_captureActionPerformed

    private void editPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPicActionPerformed

        WebcamTest t = new WebcamTest("student");
        t.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_editPicActionPerformed

    private void rollNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rollNoKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        fullName.requestFocus();
        }else{
        keyAction(evt,"submit");
        }
    }//GEN-LAST:event_rollNoKeyPressed

    private void fullNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fullNameKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        Branch.requestFocus();
        }else{
        keyAction(evt,"submit");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameKeyPressed

    private void BranchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BranchKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        year1.requestFocus();
        }else{
        keyAction(evt,"submit");
        }
      // TODO add your handling code here:
    }//GEN-LAST:event_BranchKeyPressed

    private void phonNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonNoKeyPressed

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        addrss.requestFocus();
        }else{
        keyAction(evt,"submit");
        }// TODO add your handling code here:
    }//GEN-LAST:event_phonNoKeyPressed

    private void addrssKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addrssKeyPressed

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        macAdd1.requestFocus();
        }else{
        keyAction(evt,"submit");
        }// TODO add your handling code here:
    }//GEN-LAST:event_addrssKeyPressed

    private void macAdd1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_macAdd1KeyPressed

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        macAdd2.requestFocus();
        }else{
        keyAction(evt,"submit");
        }// TODO add your handling code here:
    }//GEN-LAST:event_macAdd1KeyPressed

    private void macAdd2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_macAdd2KeyPressed

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        validUpto.requestFocus();
        }else{
        keyAction(evt,"submit");
        }// TODO add your handling code here:
    }//GEN-LAST:event_macAdd2KeyPressed

    private void validUptoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validUptoKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        capture.requestFocus();
        }else{
        keyAction(evt,"submit");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_validUptoKeyPressed

    private void captureKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_captureKeyPressed

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        submit.requestFocus();
        }
        else{
        keyAction(evt,"submit");
        }// TODO add your handling code here:
    }//GEN-LAST:event_captureKeyPressed

    private void submitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_submitKeyPressed

        keyAction(evt,"submit");// TODO add your handling code here:
    }//GEN-LAST:event_submitKeyPressed

    private void deleteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deleteKeyPressed

        keyAction(evt, "reset");// TODO add your handling code here:
    }//GEN-LAST:event_deleteKeyPressed

    private void cancelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cancelKeyPressed

        keyAction(evt, "cancel");// TODO add your handling code here:
    }//GEN-LAST:event_cancelKeyPressed

    private void year1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_year1KeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        phonNo.requestFocus();
        }else{
        keyAction(evt,"submit");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_year1KeyPressed
void submit()
{
    if(putStudentInfo()){
          if(action.equalsIgnoreCase("edit")){
              StudentDetailsForm stdDetail = new StudentDetailsForm("edit");
              stdDetail.setVisible(true);
              
          }
          if(action.equalsIgnoreCase("delete")){
              StudentDetailsForm stdDetail = new StudentDetailsForm("delete");
              stdDetail.setVisible(true);
              
          }
          else if(action.equalsIgnoreCase("")){
        StudentDetailsForm stdDetail = new StudentDetailsForm(1);
        stdDetail.setVisible(true);
        
      }
               this.dispose();
    }
}
    
     
    boolean putStudentInfo(){
    if(Validation.val.validateStudentInfo(this.rollNo.getText(),this.fullName.getText(),this.Branch.getSelectedItem().toString(),this.year1.getSelectedItem().toString(),this.phonNo.getText(),this.addrss.getText(),this.macAdd1.getText(),this.macAdd2.getText(),this.validUpto.getText()) == true){            
        //if(Validation.val.validateStudentInfo(this.rollNo.getText(),this.fullName.getText(),this.Branch.getSelectedItem().toString(),this.year1.getSelectedItem().toString(),this.phonNo.getText(),this.addrss.getText(),this.macAdd1.getText(),this.macAdd2.getText()) == true){            
        Student.std.name = this.fullName.getText();
        Student.std.id = this.rollNo.getText();
        Student.std.address = this.addrss.getText();
        Student.std.branch = this.Branch.getSelectedItem().toString();
        Student.std.phone = this.phonNo.getText();
        Student.std.year = Integer.parseInt(this.year1.getSelectedItem().toString());
        Student.std.macAdd1 = this.macAdd1.getText();
        Student.std.macAdd2 = this.macAdd2.getText();
        Student.std.validUpto = Integer.parseInt(this.validUpto.getText());
         if(!action.equalsIgnoreCase("edit")){
        Student.std.addedby = Session.s1.sessionUser;
        Student.std.addtimestamp = TimeDate.time.timestampToFullDate(TimeDate.time.currentTimeStamp());
        }
        Student.std.password = this.rollNo.getText();
        
        return true;
        }
    else 
        return false;

    }
    void resetItems(){
        //enableItems();        
        this.rollNo.setText("");
        this.fullName.setText("");
        this.Branch.setSelectedIndex(0);
        this.year1.setSelectedIndex(0);
        this.phonNo.setText("");
        this.addrss.setText("");
        this.macAdd1.setText("");
        this.macAdd2.setText("");
    }
     void getPrevious()
     {  this.rollNo.setText(Student.std.id );
        this.fullName.setText(Student.std.name);
        this.Branch.setSelectedItem(Student.std.branch);
        this.year1.setSelectedItem(((Integer)Student.std.year).toString());
        this.phonNo.setText(Student.std.phone );
        this.addrss.setText(Student.std.address);
        this.macAdd1.setText(Student.std.macAdd1 );
        this.macAdd2.setText(Student.std.macAdd2);
        this.validUpto.setText(((Integer)Student.std.validUpto).toString());
     }
     void keyAction(java.awt.event.KeyEvent evt, String Button) {
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            if (Button.equalsIgnoreCase("cancel")) {
                int i=DialogBox.dialog.confirmDialog("All the details will get lost.. Do you want to cancel ??");
             if(i==0)
             {
                 this.dispose();
             }
             else if(i==1){}
             else if(i==2){}
            } 
            else if (Button.equalsIgnoreCase("submit")) {
                submit();
            }
            else if (Button.equalsIgnoreCase("reset")) {
                resetItems();
            }
            else{
            submit();
            }
        }
        if (key == KeyEvent.VK_ESCAPE) {    
             int i=DialogBox.dialog.confirmDialog("All the details will get lost.. Do you want to cancel ??");
             if(i==0)
             {
                 this.dispose();
             }
             else if(i==1){}
             else if(i==2){}
            }
    }
         /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Branch;
    private javax.swing.JLabel address;
    private javax.swing.JTextField addrss;
    private javax.swing.JLabel branch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel;
    private javax.swing.JToggleButton capture;
    private javax.swing.JButton delete;
    private javax.swing.JButton editPic;
    private javax.swing.JTextField fullName;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField macAdd1;
    private javax.swing.JTextField macAdd2;
    private javax.swing.JLabel macadd1;
    private javax.swing.JLabel macadd2;
    protected javax.swing.JLabel mainlbl;
    private javax.swing.JTextField phonNo;
    private javax.swing.JLabel phonno;
    private javax.swing.JPanel photo;
    private javax.swing.JPanel photoPanel;
    private javax.swing.JLabel pic;
    private javax.swing.JTextField rollNo;
    private javax.swing.JLabel rollno;
    private javax.swing.JButton submit;
    private javax.swing.JTextField validUpto;
    private javax.swing.JLabel validupto;
    private javax.swing.JLabel year;
    private javax.swing.JComboBox year1;
    // End of variables declaration//GEN-END:variables
}
