/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * studentFormMain.java
 *
 * Created on Jan 19, 2012, 7:04:58 PM
 */
package test;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
/**
 *
 * @author Achyut
 */
public class StudentFormMain extends javax.swing.JFrame {
   BufferedImage im;
    /** Creates new form studentFormMain */
    public StudentFormMain() {
        
        initComponents();
        Thread thd = new Thread(){
        public void run(){
        TimeDate tmd = new TimeDate();
        while(true){
                    try {
                        timeLabel.setText(tmd.timestampToFullDate(System.currentTimeMillis()));
                            sleep(1000);
                    } catch (InterruptedException ex) {
                        Log.log.writeErrorLog(ex.getMessage(),"InchargeFormMain","constructor");
                    }
                }
            }
        };
        thd.start();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        
      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        detais = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        validupto = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        photoPanel = new javax.swing.JPanel();
        pic = new javax.swing.JLabel();
        statusImage = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        checkoutid = new javax.swing.JTextField();
        checkoutname = new javax.swing.JTextField();
        checkOutButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        checkoutreset = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        checkinid = new javax.swing.JTextField();
        checkinname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        checkinreset = new javax.swing.JButton();
        checkInButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        searchid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        searchReset = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        titleText = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar3.add(jMenu8);

        jMenu10.setText("File");
        jMenuBar4.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar4.add(jMenu11);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(": : Apley Authentication Systems [Student Main] : :");
        setBackground(new java.awt.Color(0, 0, 51));
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel1.setAutoscrolls(true);

        jPanel3.setPreferredSize(new java.awt.Dimension(1221, 735));

        jLabel5.setFont(new java.awt.Font("College", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("Apely Distributed Authentication Systems");
        jLabel5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel5keyPressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/apely_logo.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Logout");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11logoutButtonClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel4.setText("Welcome "+Session.s1.sessionUser);

        timeLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        timeLabel.setText("Time");
        timeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        timeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeLabellogoutButtonClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel22.setText("Current Date/Time:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 199, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(189, 189, 189))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel5))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(7, 7, 7))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("© National Institute of Technology, Kurukshetra - 136119");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Developed By:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Achyut Paudel");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Lovely Gupta");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Special Thanks To:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Rachit");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(281, 281, 281)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(58, 58, 58)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(59, 59, 59))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        detais.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 2, true), "Personal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 102, 204))); // NOI18N
        detais.setForeground(new java.awt.Color(0, 102, 102));
        detais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                detaiskeyPressed(evt);
            }
        });
        detais.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("ID:");
        detais.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        Id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Id.setForeground(new java.awt.Color(153, 0, 0));
        detais.add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 100, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Name:");
        detais.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 20));

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(153, 0, 0));
        detais.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 90, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Address:");
        detais.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        address.setForeground(new java.awt.Color(153, 0, 0));
        detais.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 290, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Valid Upto:");
        detais.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        validupto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        validupto.setForeground(new java.awt.Color(153, 0, 0));
        detais.add(validupto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 100, 20));
        detais.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 830, 20));
        detais.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, -1));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        detais.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 10, 170));

        photoPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout photoPanelLayout = new javax.swing.GroupLayout(photoPanel);
        photoPanel.setLayout(photoPanelLayout);
        photoPanelLayout.setHorizontalGroup(
            photoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        );
        photoPanelLayout.setVerticalGroup(
            photoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(photoPanelLayout.createSequentialGroup()
                .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        detais.add(photoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, 120));

        statusImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        detais.add(statusImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 80, 70));

        msg.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        msg.setForeground(new java.awt.Color(51, 153, 0));
        msg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        detais.add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 570, 60));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 2, true), "Check Out", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 102, 204))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("ID/ Roll No:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Name :");

        checkoutid.setBackground(java.awt.SystemColor.info);
        checkoutid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkoutid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        checkoutid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checkoutidKeyPressed(evt);
            }
        });

        checkoutname.setBackground(java.awt.SystemColor.info);
        checkoutname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkoutname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        checkoutname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checkoutnameKeyPressed(evt);
            }
        });

        checkOutButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/checkout.png"))); // NOI18N
        checkOutButton.setText("Check Out");
        checkOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutButtonActionPerformed(evt);
            }
        });
        checkOutButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checkOutButtonKeyPressed(evt);
            }
        });

        checkoutreset.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkoutreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/refresh.png"))); // NOI18N
        checkoutreset.setText("Reset");
        checkoutreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutresetActionPerformed(evt);
            }
        });
        checkoutreset.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checkoutresetKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(checkOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkoutreset, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(52, 52, 52)
                        .addComponent(checkoutname))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(checkoutid))
                    .addComponent(jSeparator3))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(checkoutid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(checkoutname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkoutreset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 2, true), "Check In", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 102, 204))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("ID/ Roll No:");

        checkinid.setBackground(java.awt.SystemColor.info);
        checkinid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkinid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        checkinid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checkinidKeyPressed(evt);
            }
        });

        checkinname.setBackground(java.awt.SystemColor.info);
        checkinname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkinname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        checkinname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checkinnameKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Name :");

        checkinreset.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkinreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/refresh.png"))); // NOI18N
        checkinreset.setText("Reset");
        checkinreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinresetActionPerformed(evt);
            }
        });
        checkinreset.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checkinresetKeyPressed(evt);
            }
        });

        checkInButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/checkin.png"))); // NOI18N
        checkInButton.setText("Check In");
        checkInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInButtonActionPerformed(evt);
            }
        });
        checkInButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checkInButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkinname, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(checkinid)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(checkInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(checkinreset, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(checkinid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(checkinname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkinreset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 2, true), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 102, 204))); // NOI18N

        searchid.setBackground(java.awt.SystemColor.info);
        searchid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        searchid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchidKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("ID :");

        searchReset.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/refresh.png"))); // NOI18N
        searchReset.setText("Reset");
        searchReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchResetActionPerformed(evt);
            }
        });
        searchReset.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchResetKeyPressed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/search_tool.png"))); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        searchButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(searchid))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchReset, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchReset, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nitLogo.png"))); // NOI18N

        titleText.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        titleText.setForeground(new java.awt.Color(0, 0, 51));
        titleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleText.setText("centre of computing and Networking");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("National Institute of Technology, Kurukshetra");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(detais, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(titleText)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(173, 173, 173)))
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(titleText)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(detais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1265, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/48/home.png"))); // NOI18N
        jMenu1.setText("Home");
        jMenu1.setFont(new java.awt.Font("SansSerif", 0, 17)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(10, 10, 10, 10));

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/logout.png"))); // NOI18N
        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1click(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/exit.png"))); // NOI18N
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2exitMenuButton(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar5.add(jMenu1);

        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/48/help.png"))); // NOI18N
        jMenu13.setText("Help");
        jMenu13.setFont(new java.awt.Font("SansSerif", 0, 17)); // NOI18N
        jMenu13.setMargin(new java.awt.Insets(10, 10, 10, 10));

        jMenuItem20.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/help_contents.png"))); // NOI18N
        jMenuItem20.setText("Help Content");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem20);

        jMenuItem21.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/32/about.png"))); // NOI18N
        jMenuItem21.setText("About");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem21);

        jMenuBar5.add(jMenu13);

        setJMenuBar(jMenuBar5);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1click

        Session.s1.closeSession();
        Authenticate1 A1 = new Authenticate1();
        A1.setVisible(true);
        //A1.reset();
        this.dispose();
    }//GEN-LAST:event_jMenuItem1click

    private void jMenuItem2exitMenuButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2exitMenuButton

        Session.s1.closeSession();
        DatabaseMain.db.database_close();
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2exitMenuButton

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed

        About abt=new About();
        abt.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jLabel5keyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel5keyPressed
        resetPanel();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5keyPressed

    private void jLabel11logoutButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11logoutButtonClicked
        this.setVisible(false);
        Session.s1.closeSession();
        Authenticate1 A1 = new Authenticate1();
        A1.setVisible(true);
        //  A1.reset();
        this.dispose();
    }//GEN-LAST:event_jLabel11logoutButtonClicked

    private void detaiskeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_detaiskeyPressed
        resetPanel();        // TODO add your handling code here:
    }//GEN-LAST:event_detaiskeyPressed

    private void checkOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutButtonActionPerformed
         if(checkoutid.getText().isEmpty() && checkoutname.getText().isEmpty()){
                   DialogBox.dialog.errorDialog("Both ID and Name Field cannot be empty");
               }
                   else if(checkoutid.getText().isEmpty() && !checkoutname.getText().isEmpty()){
               DuplicateName nameTable = new DuplicateName(checkoutname.getText(),"all");
               nameTable.setVisible(true);
               }
               else{
               checkout();
               }
    }//GEN-LAST:event_checkOutButtonActionPerformed

    private void checkoutresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutresetActionPerformed

        resetout();// TODO add your handling code here:
    }//GEN-LAST:event_checkoutresetActionPerformed

    private void checkinresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkinresetActionPerformed

        resetin();// TODO add your handling code here:
    }//GEN-LAST:event_checkinresetActionPerformed

    private void checkInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInButtonActionPerformed
    AbstractPerson.ab.checkStatus();
        AbstractPerson.ab.checkBlacklist();
        if(checkinid.getText().isEmpty() && checkinname.getText().isEmpty()){
                   DialogBox.dialog.errorDialog("Both ID and Name Field cannot be empty");
               }
               else if(checkinid.getText().isEmpty() && !checkinname.getText().isEmpty()){
               DuplicateName name = new DuplicateName(checkinname.getText(),"all");
               name.setVisible(true);
               }
               else{
               checkin();
               }
        
    }//GEN-LAST:event_checkInButtonActionPerformed
    private void checkin(){
    int i=AbstractPerson.ab.checkinValidate(this.checkinid.getText(),this.checkinname.getText());
                               if (i==1) {
                                    setStudentDetails(this.checkinid.getText(), this.checkinname.getText());
                                    this.msg.setText("Succesfully checked in");
                                  this.msg.setForeground(Color.green.darker());
                                    resetin();
                               }
                               else if (i==2){
                                    setFacultyDetails(this.checkinid.getText(), this.checkinname.getText());
                                    this.msg.setText("Succesfully checked in");
                                    this.msg.setForeground(Color.green.darker());
                                    resetin();      
                                    }
                               else if (i==3){
                                    setGuestDetails(this.checkinid.getText(), this.checkinname.getText());
                                   this.msg.setText("Succesfully checked in");
                                  this.msg.setForeground(Color.green.darker());
                                   resetin();
                                    }
                               else if(i==4){
                                    resetPanel();
                                    this.msg.setText("Person with given details is not found!!");
                                    this.msg.setForeground(Color.red);
                                    setErrorImage();
                                  }
                                else if(i==5){
                                resetPanel();
                                this.msg.setText("Your Validity has expired.");
                                this.msg.setForeground(Color.red);
                                setErrorImage();
                                resetin();
                         }
                                else if(i==6){
                                this.resetin();
                                resetPanel();
                                this.msg.setText("Already checked in!!");
                                this.msg.setForeground(Color.red);
                                setErrorImage();
                                }
                              else if(i==7){
                            resetPanel();
                            this.msg.setForeground(Color.red);
                            this.msg.setText("You are blacklisted!!.So,Can't checkin");
                            setErrorImage();
                            this.resetin();
                                }

                         else if(i==8){
                        resetPanel();
                        this.msg.setForeground(Color.red);
                        this.msg.setText("Incorrect details entered!!");
                        setErrorImage();
                        }
                         else if(i==9){
                        resetPanel();
                        this.msg.setText("Person with given details is not found.");
                        this.msg.setForeground(Color.red);
                        setErrorImage();
                        }

    }
    private void checkout(){
            int i = AbstractPerson.ab.checkoutValidate(this.checkoutid.getText(), this.checkoutname.getText());
        ResultSet rs = null;
        if (i == 1) {
            try {
                rs = Student.std.getStudentInfo(this.checkoutid.getText(), this.checkoutname.getText());
                this.Id.setText(rs.getString("studentid"));
                this.name.setText(rs.getString("name"));
                this.address.setText(rs.getString("address"));
                this.validupto.setText(((Integer) rs.getInt("validupto")).toString());
                this.msg.setText("successfully checked out!!");
                this.msg.setForeground(Color.green.darker());
                setImage(rs);
                setSuccessImage();
            } catch (Exception e) {
                DialogBox.dialog.errorDialog(e.getMessage());
            }
            this.resetout();
        } else if (i == 2) {
            try {
                rs = Faculty.fct.getFacultyInfo(this.checkoutid.getText(), this.checkoutname.getText());
                this.Id.setText(rs.getString("facultyid"));
                this.name.setText(rs.getString("name"));
                this.address.setText(rs.getString("address"));
                this.validupto.setText(((Integer) rs.getInt("validupto")).toString());
                setImage(rs);
                this.msg.setText("Succesfully checked out");
                this.msg.setForeground(Color.green.darker());
                setSuccessImage();
            } catch (Exception e) {
                Log.log.writeErrorLog(e.getMessage(), "InchargeFormMain", "checkOutButton");
            }
            this.resetout();
        } else if (i == 3) {
            try {
                rs = Guest.gst.getGuestInfo(this.checkoutid.getText(), this.checkoutname.getText());
                this.Id.setText(rs.getString("guestid"));
                this.name.setText(rs.getString("name"));
                this.address.setText(rs.getString("address"));
                this.validupto.setText(((Integer) rs.getInt("validupto")).toString());
                setImage(rs);
                this.msg.setText("Succesfully checked out!!");
                this.msg.setForeground(Color.green.darker());
                setSuccessImage();

            } catch (Exception e) {
                Log.log.writeErrorLog(e.getMessage(), "InchargeFormMain", "checkoutbutton");
            }
            this.resetout();
        } else if (i == 4) {
            resetPanel();
            this.msg.setText("An error occured while checking out!!");
            this.msg.setForeground(Color.red);
            setErrorImage();
        } else if (i == 5) {
            resetPanel();
            this.msg.setText("The person has not checked in.");
            this.msg.setForeground(Color.red);
            setErrorImage();
            this.resetout();
        } else if (i == 6) {
            resetPanel();
            this.msg.setText("Incorrrect details entered");
            this.msg.setForeground(Color.red);
            setErrorImage();
        } else if (i == 7) {
            resetPanel();
            this.msg.setText("A person with given details is not found.");
            this.msg.setForeground(Color.red);
            setErrorImage();
        }
    }
    private void search(){
     ResultSet rs;
        int i=AbstractPerson.ab.searchValidate(this.searchid.getText());
                if (i==1){
                    setStudentDetails(this.searchid.getText(), "");
                    setSuccessImage();
                    this.msg.setText("Record Found");
                    this.msg.setForeground(Color.green.darker());
                    this.resetsearch();
                } else if (i==2){
                    setFacultyDetails(this.searchid.getText(), "");
                    setSuccessImage();
                    this.msg.setText("Record Found");
                    this.msg.setForeground(Color.green.darker());
                    this.resetsearch();
                } else if (i==3){
                    setGuestDetails(this.searchid.getText(), "");
                    setSuccessImage();
                    this.msg.setText("Record Found");
                    this.msg.setForeground(Color.green.darker());
                    this.resetsearch();
                } else if(i==4){
                    resetPanel();
                    this.msg.setText("Person with given details is not found!!");
                    this.msg.setForeground(Color.red);
                    setErrorImage();
                }
                else if(i==5){
                resetPanel();
                this.msg.setText("Person with id= " + this.searchid.getText() + " doesn't exist!!");
                this.msg.setForeground(Color.red);
                setErrorImage();
                   }

    }
    private void searchResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchResetActionPerformed

        resetsearch();// TODO add your handling code here:
    }//GEN-LAST:event_searchResetActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
    search();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed

        try {
        File myFile = new File("helpfile.pdf");
        Desktop.getDesktop().open(myFile);
    } catch (IOException ex) {
        Log.log.writeErrorLog(ex.getMessage(), "StudentFormMain","Click helpfile menu");
        // no application registered for PDFs
    }        // TODO add your handling code here:// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void timeLabellogoutButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeLabellogoutButtonClicked

   }//GEN-LAST:event_timeLabellogoutButtonClicked

    private void checkinidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_checkinidKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        checkin();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_checkinidKeyPressed

    private void checkinnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_checkinnameKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        checkin();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_checkinnameKeyPressed

    private void checkInButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_checkInButtonKeyPressed

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        checkin();
        }// TODO add your handling code here:
    }//GEN-LAST:event_checkInButtonKeyPressed

    private void checkinresetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_checkinresetKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        resetin();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_checkinresetKeyPressed

    private void checkoutidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_checkoutidKeyPressed

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        checkout();
        }// TODO add your handling code here:
    }//GEN-LAST:event_checkoutidKeyPressed

    private void checkoutnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_checkoutnameKeyPressed

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        checkout();
        }// TODO add your handling code here:
    }//GEN-LAST:event_checkoutnameKeyPressed

    private void checkOutButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_checkOutButtonKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        checkout();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_checkOutButtonKeyPressed

    private void checkoutresetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_checkoutresetKeyPressed

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
            resetout();
        }// TODO add your handling code here:
    }//GEN-LAST:event_checkoutresetKeyPressed

    private void searchidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchidKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        search();
        }
        
    }//GEN-LAST:event_searchidKeyPressed

    private void searchButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchButtonKeyPressed

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        search();
        }
    }//GEN-LAST:event_searchButtonKeyPressed

    private void searchResetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchResetKeyPressed

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {   
        resetsearch();
        }// TODO add your handling code here:
    }//GEN-LAST:event_searchResetKeyPressed


  void setStudentDetails(String id,String name)
    {   ResultSet rs=null;
        try{
                        rs= Student.std.getStudentInfo(id,name);
                        this.Id.setText(rs.getString("studentid"));
                        this.name.setText(rs.getString("name"));
                        this.address.setText(rs.getString("address"));
                        this.validupto.setText(((Integer)rs.getInt("validupto")).toString());
                        setImage(rs);
                        setSuccessImage();
                                  }
                        catch(Exception e){Log.log.writeErrorLog(e.getMessage(), "StudentFormMain", "setStudentDetails");}
                                
    }
    void setGuestDetails(String id,String name){
        ResultSet rs;
         try{
                        rs= Guest.gst.getGuestInfo(id,name);
                        this.Id.setText(rs.getString("guestid"));
                        this.name.setText(rs.getString("name"));
                        this.address.setText(rs.getString("address"));
                        this.validupto.setText(((Integer)rs.getInt("validupto")).toString());
                        setImage(rs);
                        setSuccessImage();
                        }
                        catch(Exception e){Log.log.writeErrorLog(e.getMessage(), "StudentFormMain", "setGuestDetails");}
                        
    }
    void setFacultyDetails(String id,String name){
        ResultSet rs;
        try{
                        rs= Faculty.fct.getFacultyInfo(id,name);
                        this.Id.setText(rs.getString("facultyid"));
                        this.name.setText(rs.getString("name"));
                        this.address.setText(rs.getString("address"));
                        this.validupto.setText(((Integer)rs.getInt("validupto")).toString());
                        setImage(rs);
                        setSuccessImage();
                        }
                        catch(Exception e){Log.log.writeErrorLog(e.getMessage(), "StudentFormMain", "setFacultyDetails");}
                        
    }
    
    
        void setImage(ResultSet rs){
                BufferedImage image=null;
                  try{
                      InputStream is = rs.getBinaryStream("image");
                        if (is != null) {
                        image = ImageIO.read(is);
                             } else {
                        File f = new File("src\\icon\\default.jpg");
                        image = ImageIO.read(f);
                        }
                        if(image != null){
                             ImageIcon thumbnailIcon = new ImageIcon(Utilities.util.rescaleImage(image,this.photoPanel.getWidth(),this.photoPanel.getHeight()));
                             this.pic.setIcon(thumbnailIcon);
                        }
                  }catch(Exception e){
                  Log.log.writeErrorLog(e.getMessage(), "StudentFormMain", "setImage");
                  }
        
    }

    
    void reset(){
       resetPanel();
       resetout();
       resetin();
       resetsearch();
       this.msg.setText("");
       AbstractPerson.ab.checkStatus();
       AbstractPerson.ab.checkBlacklist();

    }
    void setErrorImage()
    {  File f = new File("src\\icon\\64\\Banned64.png");
        try {
           im = ImageIO.read(f);
        } catch (IOException ex) {
           Log.log.writeErrorLog(ex.getMessage(), "StudentFormMain", "setErrorImage");
        }
    ImageIcon icn=new ImageIcon(im);
            this.statusImage.setIcon(icn);   
}
void setSuccessImage(){
    File f = new File("src\\icon\\64\\Apply64.png");
        try {
           im = ImageIO.read(f);
        } catch (IOException ex) {
           Log.log.writeErrorLog(ex.getMessage(), "StudentFormMain", "setSucessImage");
        }
    ImageIcon icn=new ImageIcon(im);
            this.statusImage.setIcon(icn);
    }
void resetsearch()
{
    this.searchid.setText("");
}    
void resetin()
    {
        this.checkinid.setText("");
        this.checkinname.setText("");
    }

    void resetout()
    {
        this.checkoutid.setText("");
        this.checkoutname.setText("");
    }
void resetPanel()
{
    this.Id.setText("");
    this.name.setText("");
    this.address.setText("");
    this.validupto.setText("");
    this.pic.setIcon(null);
    this.statusImage.setIcon(null);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Id;
    private javax.swing.JLabel address;
    private javax.swing.JButton checkInButton;
    private javax.swing.JButton checkOutButton;
    private javax.swing.JTextField checkinid;
    private javax.swing.JTextField checkinname;
    private javax.swing.JButton checkinreset;
    private javax.swing.JTextField checkoutid;
    private javax.swing.JTextField checkoutname;
    private javax.swing.JButton checkoutreset;
    private javax.swing.JPanel detais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel msg;
    private javax.swing.JLabel name;
    private javax.swing.JPanel photoPanel;
    private javax.swing.JLabel pic;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton searchReset;
    private javax.swing.JTextField searchid;
    private javax.swing.JLabel statusImage;
    public javax.swing.JLabel timeLabel;
    private javax.swing.JLabel titleText;
    private javax.swing.JLabel validupto;
    // End of variables declaration//GEN-END:variables
}
