/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;

/**
 *
 * @author Achyut
 */
public class WebcamTest extends javax.swing.JFrame {
String window;
boolean changed = false;
/**
     * Creates new form WebcamTest
     */
    public WebcamTest() {
    
    
        initComponents();
        this.setBounds(10, 10, 300, 300);
        Component video = Webcam.cam.getVideo();
        video.setSize(camPanel.getWidth(),camPanel.getHeight());
        this.camPanel.add(video,BorderLayout.CENTER);
        
        //this.add(w.getVideo());
    }
    void keyAction(java.awt.event.KeyEvent evt, String Button) {
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            if (Button.equalsIgnoreCase("cancel")) {
                this.dispose();
            } else if (Button.equalsIgnoreCase("submit")) {
                capture();
            }
        }
        if (key == KeyEvent.VK_ESCAPE) {
            Webcam.cam.closeCam();
            this.dispose();
        }
    }
    public WebcamTest(String win) {
        initComponents();
        window = win;
        this.setBounds(10, 10, 300, 300);
        Component video = Webcam.cam.getVideo();
        video.setSize(camPanel.getWidth(),camPanel.getHeight());
        this.camPanel.add(video,BorderLayout.CENTER);
        
        //this.add(w.getVideo());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        camPanel = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        captureButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(": : Webcam : :");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                windowclosed(evt);
            }
        });

        javax.swing.GroupLayout camPanelLayout = new javax.swing.GroupLayout(camPanel);
        camPanel.setLayout(camPanelLayout);
        camPanelLayout.setHorizontalGroup(
            camPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );
        camPanelLayout.setVerticalGroup(
            camPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );

        jButton4.setText("close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });

        captureButton.setText("Capture");
        captureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                captureButtonActionPerformed(evt);
            }
        });
        captureButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                captureButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(camPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(captureButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(camPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(captureButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Webcam.cam.stopCam();        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed
    void capture(){
    if(captureButton.isSelected()){
           Webcam.cam.captureImage();
           BufferedImage bi = Webcam.cam.getBufferedImage();
          if(window.equalsIgnoreCase("student")){
           Student.std.image = bi;
          }
          else if(window.equalsIgnoreCase("guest")){
              Guest.gst.image = bi;
          }
          else if(window.equalsIgnoreCase("faculty")){
              Faculty.fct.image = bi;
          }
           Webcam.cam.stopCam();
        }
        else if(!captureButton.isSelected())
        {
           Webcam.cam.startCam();
        }
    }
    private void captureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_captureButtonActionPerformed
        capture();
        // TODO add your handling code here:
    }//GEN-LAST:event_captureButtonActionPerformed

    private void windowclosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowclosed

        Webcam.cam.closeCam();
        // TODO add your handling code here:
    }//GEN-LAST:event_windowclosed

    private void captureButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_captureButtonKeyPressed

        keyAction(evt, "submit");// TODO add your handling code here:
    }//GEN-LAST:event_captureButtonKeyPressed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed

        keyAction(evt, "cancel");// TODO add your handling code here:
    }//GEN-LAST:event_jButton4KeyPressed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel camPanel;
    private javax.swing.JToggleButton captureButton;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
